version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: aerouser
      POSTGRES_PASSWORD: aeropass
      POSTGRES_DB: aerodb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
